### PR TITLE
feat: close fzf selection if backspace is pressed on empty input

### PR DESCRIPTION
**Pull request by qoomon**

### CODE REVIEW

**Comment by qoomon** [comment]
@Aloxaf any feedback?

**Comment by yrammos** [comment]
@qoomon I think this setting pertains to `fzf`, not `fzf-tab`. Have you tried binding backspace to the `backward-delete-char/eof` action?

`fzf --bind=bspace:backward-delete-char/eof`

**Comment by qoomon** [comment]
> Have you tried binding backspace to the backward-delete-char/eof action?

@yrammos that's exactly what I did in this PR

**Comment by yrammos** [comment]
Oops, indeed -- sorry!

**Comment by Aloxaf** [comment]
That's good! 

But I suggest moving it here, so that user can override it if they want:
https://github.com/Aloxaf/fzf-tab/blob/f95cdcf2c390428d271f2304698c2d45f0cd4de5/lib/-ftb-fzf#L31

**Comment by qoomon** [comment]
@Aloxaf done.

**Pull request merged**
