### PR TITLE
Continuous completion

### PR DESCRIPTION
**Pull request by Aloxaf**
Use '/' to trigger

### CODE REVIEW

**Comment by romkatv** [comment]
Would it be possible to use a different binding by default? Perhaps `alt-enter`? With the current binding it's no longer possible to type `/` in fzf.

**Comment by nasyxx** [comment]
I guess there should be no "/" in the file name, which makes it is exact to use `/` as the default binding.

**Comment by romkatv** [comment]
> I guess there should be no "/" in the file name, which makes it is exact to use `/` as the default binding.

Completion candidates can contain "/" both in their values and in descriptions.

**Comment by Aloxaf** [comment]
I will make it configurable.

**Comment by romkatv** [comment]
Thank you!

**Pull request merged**
