### PR TITLE
feat: swap tab and btab direction when tmux-popup shows above the cursor

### PR DESCRIPTION
**Pull request by zyf0330**
Do you think this is a good change?

### CODE REVIEW

**Comment by Aloxaf** [comment]
Quite reasonable.

**Comment by tardypad** [comment]
I think this commit should be reverted because it doesn't follow the usual behavior of fzf.
fzf doesn't invert the meaning of `up` and `down` actions depending on the layout.
So this brings inconsistencies in the usage of fzf.
For example when used in fzf-tab with a default layout `tab` goes up visually but in other instances, it would go down.

Personnally this change broke the usage of fzf-tab because I force fzf to use reverse layout by default.

**Comment by Aloxaf** [comment]
@tardypad 
Thanks for your advice. I add a option named `popup-smart-tab` to control this behavior.
You can use `zstyle ':fzf-tab:complete:*' popup-smart-tab false` to disable it now.

**Comment by tardypad** [comment]
@Aloxaf Thanks for the really quick change.
I can live with this workaround :)

**Pull request merged**
