### PR TITLE
feat: more powerful preview

### LINKED ISSUE #79: Tag specific preview and cycling
**Is your feature request related to a problem? Please describe.**
Im trying to define different preview specific to the type/tag of the completion, for example it can be either a command / folder / textfile / image / aliases
`vim `
**Describe the solution you'd like**
Actually Im using
```zsh
zstyle ':fzf-tab:complete:*' extra-opts --preview=$extract'

  # Display Information about the command
  which ${~ctxt[hpre]}$in | grep -v "not found" 2> /dev/null;
  whatis ${~ctxt[hpre]}$in 2> /dev/null;

  # Search through man and give the description segment
 man "${~ctxt[hpre]}$in" 2> /dev/null |col -bx|awk -v S="$2" "DESCRIPTION ~ S {cap="true"; print} DESCRIPTION !~ S && /^[A-Z ]+$/ {cap="false"} DESCRIPTION !~ S && !/^[A-Z ]+$/ {if(cap == "true")print}" 2> /dev/null;

  # Display images
  tiv -h ${FZF_PREVIEW_LINES} -w ${FZF_PREVIEW_COLUMNS} ${~ctxt[hpre]}$in  2> /dev/null;

  # Display exif data
  # exiftool ${~ctxt[hpre]}$in  2> /dev/null;
  
  # Display directory
  lsd --tree --depth 2 --color=always ${~ctxt[hpre]}$in 2> /dev/null
  # exa -1 --color=always ${~ctxt[hpre]}$in 2> /dev/null;
  # du -h ${~ctxt[hpre]}$in 2> /dev/null | tail -n1

  # Display file
  bat --theme="OneHalfDark" --style=numbers,changes --color always ${~ctxt[hpre]}$in 2> /dev/null | head -n50 | grep -v "bat warning";
  '

```

I would like to be able to handle all kind of completion types like options / commits / users / services / diff / urls.
So the extra ops should have a way to know which kind of tag is previewed.

Hence thoses questions that are in the way: 

1. How to make preview that are aware of the current tag to display?
2. How to make functions available inside zstyle? (I tryed to define functions just above be I couldnt use theme)
3. How to make aliases available inside zstyle? (`which g` work inside a shell but not when im trying to show it during the completion preview)
4. How would you implement a way to switch the preview mode (for example the type `imageFile` would have 2 preview mode: `exif` and `terminal preview`)

Here is what the code above do, im using [tiv](https://github.com/stefanhaustein/TerminalImageViewer) for the image display and [bat](https://github.com/sharkdp/bat) for the code 
fzf-tab

git diff

### PR DESCRIPTION
**Pull request by Aloxaf**
This will close #79.

Example:

```zsh
zstyle ':fzf-tab:complete:*' extra-opts --preview=$fzf_tab_preview_init'
echo word: $word
echo description: $desc
echo group: $group
if (( $+ctxt[isfile] )); then
  echo path: $realpath
fi
'
```

### CODE REVIEW

**Comment by adelin-b** [comment]
That look great :D
I tryed with my current config and I got this: with numbers at the front
image
It works fine with a minimal version so its a bug inside my zshrc,
 I will look for what is causing the group id at the starts

Other way its really good, lot of preview incoming :)

**Comment by Aloxaf** [comment]
@adelin-b I added a new argument to fzf. 
https://github.com/Aloxaf/fzf-tab/blob/ac69d23e09ec4866099b33153956b020845ae754/fzf-tab.zsh#L121

I should find a way to avoid it before merging this branch...

**Comment by adelin-b** [comment]
Zsh code is so un intuitive to understand, I tryed to hack around in it for the groups myself but it's quite hard to get what thoses expressions means.

**Comment by Aloxaf** [comment]
> Zsh code is so un intuitive to understand, I tryed to hack around in it for the groups myself but it's quite hard to get what thoses expressions means.

LOL, yes, shell script is write-only. I also spent half an hour to understand what my code has done since I haven’t paid attention to this project for three month.

**Comment by adelin-b** [comment]
Maybe you can include comments on this pr so you will understand next time

**Comment by adelin-b** [comment]
There is an issue because the strings are not escaped and we cannot get the original `hit` only the `dscr`, for example when description  has \` \` in it it will open a subshell
```
fzf_tab_preview_commit=$fzf_tab_preview_init'
# Show commits and branch commits 
case $group in 
  (*file)
    # Show commits and branch commits 
    echo $( echo "$in" | cut -f 1 -d " " )
    git diff $( echo "$in" | cut -f 1 -d " " ) | diff-so-fancy --colors 2> /dev/null
    ;;

  (*command)
    exit
    ;;

  (*)

  esac
  '

zstyle ':fzf-tab:complete:git*:*' extra-opts --preview=$fzf_tab_preview_commit
```

and now if you `git checkout [TAB]` and go over the last commits "add a special variable `fzf_tab_preview_init`"  it will try to execute fzf_tab_preview init because in the commit name there is backticks

**Comment by Aloxaf** [comment]
@adelin-b Fixed

**Comment by adelin-b** [comment]
There is currently a bug, group is lost
```
fzf_tab_preview_debug='
echo "word: $word"
echo "group: $group"
echo "dscr: $dscr"
echo "realpath: $realpath"
'
zstyle ':fzf-tab:complete:*' extra-opts --preview=$fzf_tab_preview_init$fzf_tab_preview_debug
```
image

**Comment by adelin-b** [comment]
Maybe add a test against `$fzf_tab_preview_init` and a `/tmp/fzf-tab/compcap.$$` file to alway ensure that `$fzf_tab_preview_init` is working

**Review by adelin-b — CHANGES_REQUESTED** [review]

**Comment by Aloxaf** [comment]
> There is currently a bug, group is lost
> 
> ```
> fzf_tab_preview_debug='
> echo "word: $word"
> echo "group: $group"
> echo "dscr: $dscr"
> echo "realpath: $realpath"
> '
> zstyle ':fzf-tab:complete:*' extra-opts --preview=$fzf_tab_preview_init$fzf_tab_preview_debug
> ```
> 
> image

Oh sorry I forgot to update `$fzf_tab_preview_init` after [`c88df0f` (#126)](https://github.com/Aloxaf/fzf-tab/pull/126/commits/c88df0f3597328b721cef9a99a956ee53907594b).

**Pull request merged**
